apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: mongo
    name: mongo
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: mongo
      from:
        kind: DockerImage
        name: mongo
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: mongo
    name: mongo
  spec:
    replicas: 1
    selector:
      app: mongo
      deploymentconfig: mongo
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: mongo
          deploymentconfig: mongo
      spec:
        containers:
        - image: mongo
          name: mongo
          ports:
          - containerPort: 27017
            protocol: TCP
          resources: {}
          volumeMounts:
          - name: nfs-share
            mountPath: /data/db
            subPath: openshift/db/mongo
        volumes:
        - name: nfs-share
          persistentVolumeClaim:
            claimName: nfs-pvc
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - mongo
        from:
          kind: ImageStreamTag
          name: mongo:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: mongo
    name: mongo
  spec:
    ports:
    - name: 27017-tcp
      port: 27017
      protocol: TCP
      targetPort: 27017
    selector:
      app: mongo
      deploymentconfig: mongo
  status:
    loadBalancer: {}
kind: List
metadata: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: '2018-07-14T20:34:03Z'
  labels:
    app: mongo
  name: mongo-nodeport
  namespace: flg
  resourceVersion: '328368'
  selfLink: /api/v1/namespaces/flg/services/mongo-nodeport
  uid: 3f32bd68-87a5-11e8-a003-000c29e709e7
spec:
  clusterIP: 172.30.227.30
  externalTrafficPolicy: Cluster
  ports:
    - name: 27017-tcp
      nodePort: 30017
      port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app: mongo
    deploymentconfig: mongo
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
