apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: redis
    name: redis
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: docker.io/library/redis:latest
      from:
        kind: DockerImage
        name: docker.io/library/redis:latest
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
kind: List
metadata: {}
---
apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: redis-fx
    name: redis-fx
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: redis-fx
    name: redis-fx
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: redis-fx:latest
    postCommit: {}
    resources: {}
    source:
      contextDir: redis
      git:
        uri: https://github.com/andesm/fx-system-trade.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: redis:latest
          namespace: flg
      type: Docker
    triggers:
    - github:
        secret: fftK_l5AQ1_hIamqQCdw
      type: GitHub
    - generic:
        secret: eP9LTjrOdKAYqHqCkOXO
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: redis-fx
    name: redis-fx
  spec:
    replicas: 1
    selector:
      app: redis-fx
      deploymentconfig: redis-fx
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: redis-fx
          deploymentconfig: redis-fx
      spec:
        containers:
        - image: redis-fx:latest
          name: redis-fx
          ports:
          - containerPort: 6379
            protocol: TCP
          resources: {}
          volumeMounts:
          - name: nfs-share
            mountPath: /data/db
            subPath: openshift/db/redis
          - name: redis-socket
            mountPath: /var/run/redis
        volumes:
        - name: nfs-share
          persistentVolumeClaim:
            claimName: flg-pvc
        - name: redis-socket
          hostPath:
            path: /var/run/redis
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - redis-fx
        from:
          kind: ImageStreamTag
          name: redis-fx:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: redis-fx
    name: redis-fx
  spec:
    ports:
    - name: 6379-tcp
      nodePort: 30379
      port: 6379
      protocol: TCP
      targetPort: 6379
    selector:
      app: redis-fx
      deploymentconfig: redis-fx
    type: NodePort
  status:
    loadBalancer: {}
kind: List
metadata: {}
