version: '3'

services:
  
  fx-mongo:
    image: mongo
    container_name: fx-mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - /db/mongo/fx:/data/db
      - /etc/localtime:/etc/localtime:ro 
    
  get_rate:
    build: get_rate
    container_name: get_rate
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro 

  backtest:
    build: fx-system-trade
    container_name: backtest 
    restart: always
    entrypoint: ./Fx backtest
    volumes:
      - /etc/localtime:/etc/localtime:ro 

#  backtest-retry:
#    build: fx-system-trade
#    container_name: backtest-retry
#    restart: always
#    entrypoint: ./Fx backtest-retry
#    volumes:
#      - /etc/localtime:/etc/localtime:ro 
      
  trade-practice:
    build: fx-system-trade
    container_name: trade
    restart: always
    entrypoint: ./Fx trade-practice 
    volumes:
      - /etc/localtime:/etc/localtime:ro 
    
